#!/bin/bash 
#
#PBS -N itest 
#PBS -j oe
#PBS -q s3par8c 
#PBS -l nodes=1:ppn=16
#PBS -l walltime=15:00:00

cd $PBS_O_WORKDIR

COUNTER=1
STOP=1

while [  $COUNTER -le $STOP ]; do
      dir=$COUNTER
      mkdir $dir
      cp  ci* test_* $dir/
      cd $dir/
      CALC=$COUNTER
      sed -i 's/NN/'"$CALC"'/g' *.inp
      #new=$RANDOM
      #sed -i 's/seed_to_change/'"$new"'/g' *.inp
      /s3_home/ecoccia/programs/WaveT/embem.x < test_vac_diss.inp > out 
      cd ../
      #echo Calculation done in $dir with SEED=$new >> iseed.dat
      let COUNTER=COUNTER+1
done

