#!/bin/bash 
COUNTER=1
STOP=1000

while [  $COUNTER -le $STOP ]; do
      dir=$COUNTER
      mkdir $dir 
      cp  ci* script test_* de_* nr* sp* $dir/
      cd $dir/
      CALC=$COUNTER
      sed -i 's/NN/'"$CALC"'/g' *.inp
      new=$RANDOM
      sed -i 's/seed_to_change/'"$new"'/g' *.inp
      ./script
      cd ../ 
      echo Calculation done in $dir with SEED=$new >> iseed.dat
      let COUNTER=COUNTER+1 
done
