#!/bin/bash 
#
#PBS -N deph4 
#PBS -j oe
#PBS -q s3par8c 
#PBS -l nodes=1:ppn=16
#PBS -l walltime=15:00:00

cd $PBS_O_WORKDIR

COUNTER=1
STOP=1000

while [  $COUNTER -le $STOP ]; do
      dir=$COUNTER
      mkdir $dir
      cp  ci* script test_* de_* nr* sp* $dir/
      cd $dir/
      CALC=$COUNTER
      sed -i 's/NN/'"$CALC"'/g' *.inp
      new=$RANDOM
      sed -i 's/seed_to_change/'"$new"'/g' *.inp
      ./script
      cd ../
      echo Calculation done in $dir with SEED=$new >> iseed.dat
      let COUNTER=COUNTER+1
done


#cp multiple_script $PBS_O_WORKDIR
#cp *inp* script $PBS_O_WORKDIR 
#/opt/torque413/bin/pbsdsh $PBS_O_WORKDIR/multiple_script
